import '@/styles/globals.css'
import Head from 'next/head'
import Navbar from '../components/navbar'
import Footer from '../components/footer'

export default function App ({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='description' content='Generated by create next app' />
        <title>Raps Company</title>
      </Head>
      <div className='absolute w-full'>
        <Navbar/>
      </div>
      <Component {...pageProps} />
      <Footer/>
    </>
  )
}
