import '@/styles/globals.css'
import '@/styles/animation.css'
import Head from 'next/head'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import { useEffect } from 'react'

export default function App ({ Component, pageProps }) {
  useEffect(() => {
    // const x = document.getElementById('audio')
    // x.autoplay = true
    // x.load()
  }, [])

  return (
    <>
      <Head>
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <meta name='description' content='Generated by create next app' />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true'/>
        <title>Raps Company</title>
      </Head>
      <div className='absolute w-full z-50'>
        <Navbar/>
        <audio id='audio' loop>
          <source src="/Growtopia.mp3" type="audio/mpeg"/>
        </audio>
      </div>
      <Component {...pageProps}/>
      <Footer/>
    </>
  )
}
